### PR TITLE
fixed mypy complaints in clients due to import aliases

### PR DESCRIPTION
**Pull request by mristin**

### CODE REVIEW

**Comment by mristin** [comment]
@radomsak could you please run `mypy --strict` against the Parquery code base with this change to see if this works? Please also check if all the unit tests pass; I expect no problems, but we never know.

Here is how you can test these changes locally.

Clone icontract, cd to the repo directory, create its virtual environment and then execute:
```
pip3 install -e .[dev]
python setup.py sdist
# File dist/icontract-2.0.6.tar.gz will be created
```

In a separate terminal:
```
cd {code base}/py
. venv/bin/activate # or whatever the command to activate the environment
pip3 install --upgrade {path to icontract repo}/dist/icontract-2.0.6.tar.gz
mypy --strict {list of modules}
```

**Comment by mristin** [comment]
(let's not forget to _squash_ instead of just merge)

**Comment by radomsak** [comment]
@mristin Thanks for the PR! I checked in our codebase and this change did not break anything. Unit tests are also passing. Could you please confirm that it is ready to merge?

**Comment by mristin** [comment]
@radomsak Thanks! Ready to **squash & merge** ;)

**Comment by mristin** [comment]
P.S. There is a separate PR that makes icontract compliant to mypy 0.750 --strict.

**Pull request merged**
