### PR TITLE
convert readme example into a script that can be easily copy/pasted

### PR DESCRIPTION
**Pull request by wgwz**
this might just be my personal preference but i feel that it's easy to run and work with the example this way. direct copy and paste into a script would allow you to run the example and step through each piece without losing information. i also added an example showing that "Pre-conditions fail before Post-conditions". that wasn't immediately obvious to me. of course the big assumption is that people would know how to handle the python debugger. i'd guess that more people are familiar with the terminal session. so perhaps this won't be accepted. but with some simple instructions, literally just, type "c" and press enter, you'll walk through each example while being able to inspect either the `result` or the exception that was raised for each scenario. enjoying testing out the library, thanks :-)

### CODE REVIEW

**Comment by mristin** [comment]
@wgwz thanks a lot for this! I personally never debug scripts this way, but I see how this approach is practical.

The problem is that doctest now doesn't run over it, so the code needs to be manually tested. Additionally, the reader might be confused that setting breakpoints is somehow related to icontract, while it is just there to facilitate the debugging.

What do you think about putting the script in a separate file (in `tests/test_sample_for_readme.py`?) and linking it at the end of the section just after or before the code examples? (I can also do this if you lack time, just let me know.)

**Comment by mristin** [comment]
Alternatively, let me have a look if javascript can be used. Maybe we can put the same content in different forms?

**Comment by mristin** [comment]
It seems that no javascript can be used.

**Comment by wgwz** [comment]
i'll leave it up to you to decide where it goes and if you want it. i'll be glad to adjust the PR to make that move for you. but i also recognize how it leads to another thing to maintain in the codebase. the more i'm looking at this the more i'm thinking it's probably a silly thing to add.

**Comment by mristin** [comment]
Hi @wgwz ,
I'll try to get it in tonight (CET). Could you please make sure that I am allowed to commit to the branch on your forked repo (see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by wgwz** [comment]
hey @mristin , sorry for the delay. it's been a busy week. i added you as a collaborator on my fork, so you should be able to take it from there. :-)

**Comment by mristin** [comment]
Thanks! I'll try to get it in this week!

**Comment by mristin** [comment]
Hi @wgwz ,
I'll definitely add your additional examples to the readme.

Instead of adding a script, what do you think about hosting your debug script on repl.it? (I can set that up.)

**Comment by mristin** [comment]
@wgwz I had some time this afternoon, so I jumped and created the repl.it script (see the pull request #194). I didn't know how to make you the main author of the change, so I added you as co-author -- I hope you don't mind? (Otherwise, please let me know how you would like to have your credit properly listed.)

I'll close this pull request. Please re-open if you have better ideas, or if further discussion is needed.

**Pull request closed without merging**
