### PR TITLE
disabled recursion in the contracts

### PR DESCRIPTION
**Pull request by mristin**

### CODE REVIEW

**Comment by mristin** [comment]
Fixes #126

**Comment by mristin** [comment]
@Sasha93  could you please assign @markusschmaus for the review?

**Comment by mristin** [comment]
Hi @markusschmaus ,
I added a couple of more unit tests for recursion avoidance. Now I am pretty confident that the code runs as expected.

Please let me know if you can not review the code, so that we can merge it in as-is.

**Comment by Sasha93** [comment]
> @Sasha93 could you please assign @markusschmaus for the review?

Apparently I can't, the only person that I can put as a reviewer is myself. Let me know if I should merge or wait for @markusschmaus's opinion.

**Comment by mristin** [comment]
Hi @markusschmaus,
Please give us some signal till this Wednesday 2020-04-29. Otherwise, we will merge the pull request.

**Comment by mristin** [comment]
@Sasha93 could you please squash & merge this PR  if there is no response from @markusschmaus till the end of today's office hours (16:30 CET)?

**Comment by Sasha93** [comment]
> @Sasha93 could you please squash & merge this PR if there is no response from @markusschmaus till the end of today's office hours (16:30 CET)?

I'll do it!

**Pull request merged**
