### PR TITLE
Added support for Python 3.11

### LINKED ISSUE #260: Add support for python 3.11

### PR DESCRIPTION
**Pull request by simkimsia**
Fixes #260.

### CODE REVIEW

**Comment by simkimsia** [comment]
@mristin I am trying to understand this scrutinizer and i saw it got timed out. 

image

I wish to self-remedy my own PR.

But I need some guidance. If you can help me to understand so I can self-diagnose and self-modify the PR, it will be great.

No hurry at all as I can wait.

Thank you

**Comment by mristin** [comment]
@simkimsia

> @mristin I am trying to understand this scrutinizer and i saw it got timed out.

Let me disable it.

Mypy dropped support for Python 3.7. I'll have to adapt the pre-commit script. Please give me some more time, as it is really busy around here.

**Comment by simkimsia** [comment]
> Please give me some more time, as it is really busy around here.

No worries. Take your time. Thank you for doing this python package

**Comment by mristin** [comment]
@simkimsia I upgraded the individual dependencies, as it required some tweaks and knowledge about the intricacies of the implementation.

Please rebase your pull request on the latest `master` branch, and then it should work.

Related pull requests:
* https://github.com/Parquery/icontract/pull/264
* https://github.com/Parquery/icontract/pull/265
* https://github.com/Parquery/icontract/pull/266
* https://github.com/Parquery/icontract/pull/267
* https://github.com/Parquery/icontract/pull/268

**Comment by simkimsia** [comment]
@mristin I have made the changes. So now waiting for approval.

Branch no longer has conflicts

Also I noticed that you have a consistent style for writing the commit message which I have tried to follow.

Do you mind if I contribute to a doc that explains explicitly the commit message style? I have written this as separate issue at #270

**Pull request merged**
